const fs = require('fs');
const path = require('path');

const seedFilePath = path.join(__dirname, './seed.js');
let content = fs.readFileSync(seedFilePath, 'utf8');

// Additional 60 Products Data Array
const additionalProductsCode = `
      // --- ADDITIONAL REAL-LIFE US MARKETPLACE PRODUCTS (TOTAL 100+ ITEMS) ---
      {
        name: 'Five Guys Bacon Cheeseburger & Cajun Fries Combo Meal',
        sku: 'PRD-FF-09',
        category: catFastFood._id,
        description: 'Two handcrafted patties grilled to order with crispy applewood smoked bacon and American cheese on a toasted sesame seed bun with spicy Cajun fries.',
        short_description: 'Five Guys Bacon Cheeseburger & Cajun Fries meal.',
        price_coins: 17250,
        images: ['https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=500'],
        stock: 100,
        weight_kg: 1.3,
        dimensions: { length_cm: 25, width_cm: 20, height_cm: 12 },
        package_type: 'box',
        fragile: false,
        featured: true
      },
      {
        name: 'Chipotle Chicken Burrito Bowl with Fresh Guacamole',
        sku: 'PRD-FF-10',
        category: catFastFood._id,
        description: 'Adobo-marinated grilled chicken over cilantro-lime brown rice, black beans, fresh tomato salsa, Monterey Jack cheese, and handmade guacamole.',
        short_description: 'Chipotle Chicken Burrito Bowl with Guacamole.',
        price_coins: 18000,
        images: ['https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=500'],
        stock: 90,
        weight_kg: 1.1,
        dimensions: { length_cm: 22, width_cm: 22, height_cm: 10 },
        package_type: 'box',
        fragile: false,
        featured: true
      },
      {
        name: 'Dunkin\' Assorted Glazed & Frosted Donuts Box (12 Pack)',
        sku: 'PRD-FF-11',
        category: catFastFood._id,
        description: 'One dozen fresh donuts including chocolate frosted, Boston Kreme, powdered jelly, and old fashioned glazed.',
        short_description: 'Dunkin\' Assorted Donuts Box (12 Pack).',
        price_coins: 18750,
        images: ['https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=500'],
        stock: 80,
        weight_kg: 1.2,
        dimensions: { length_cm: 35, width_cm: 25, height_cm: 8 },
        package_type: 'box',
        fragile: false,
        featured: false
      },
      {
        name: 'Domino\'s Ultimate Meat Lovers Hand-Tossed Pizza (14")',
        sku: 'PRD-FF-12',
        category: catFastFood._id,
        description: 'Topped with pepperoni, Italian sausage, ham, savory beef, and smoked bacon on a garlic-seasoned crust.',
        short_description: 'Domino\'s Ultimate Meat Lovers 14" Pizza.',
        price_coins: 19500,
        images: ['https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=500'],
        stock: 75,
        weight_kg: 1.7,
        dimensions: { length_cm: 36, width_cm: 36, height_cm: 10 },
        package_type: 'box',
        fragile: false,
        featured: true
      },
      {
        name: 'Tea Forté Organic Herbal Tea Tasting Chest (40 Pyramids)',
        sku: 'PRD-GIF-13',
        category: catGifts._id,
        description: 'Luxury presentation box with 40 handcrafted silk pyramid tea infusers featuring 20 organic herbal & black tea blends.',
        short_description: 'Tea Forté Organic Tea Tasting Chest (40 Pyramids).',
        price_coins: 28500,
        images: ['https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500'],
        stock: 60,
        weight_kg: 1.2,
        dimensions: { length_cm: 30, width_cm: 22, height_cm: 10 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Harry & David Royal Riviera Pears Luxury Gift Box',
        sku: 'PRD-GIF-14',
        category: catGifts._id,
        description: 'Nine famous sweet, juicy Royal Riviera Pears grown in Oregon orchards, hand-picked and gold foil wrapped.',
        short_description: 'Harry & David Royal Riviera Pears Gift Box.',
        price_coins: 31500,
        images: ['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=500'],
        stock: 50,
        weight_kg: 2.8,
        dimensions: { length_cm: 32, width_cm: 25, height_cm: 12 },
        package_type: 'box',
        fragile: true,
        featured: false
      },
      {
        name: 'Fresh Premium Red Roses & White Lilies Floral Bouquet',
        sku: 'PRD-GIF-15',
        category: catGifts._id,
        description: '12 long-stemmed Ecuadorian red roses paired with oriental white lilies and eucalyptus greens in a glass vase.',
        short_description: 'Red Roses & White Lilies Fresh Bouquet.',
        price_coins: 34500,
        images: ['https://images.unsplash.com/photo-1561181286-d3fee7d55364?w=500'],
        stock: 45,
        weight_kg: 2.0,
        dimensions: { length_cm: 45, width_cm: 25, height_cm: 20 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Hickory Farms Beef Sausage & Smoked Cheese Gift Basket',
        sku: 'PRD-GIF-16',
        category: catGifts._id,
        description: 'Signature beef summer sausages, smoked gouda, farm cheddar, sweet hot mustard, and toasted crackers.',
        short_description: 'Hickory Farms Beef & Cheese Gift Basket.',
        price_coins: 37500,
        images: ['https://images.unsplash.com/photo-1544816155-12df9643f363?w=500'],
        stock: 55,
        weight_kg: 3.0,
        dimensions: { length_cm: 35, width_cm: 28, height_cm: 14 },
        package_type: 'box',
        fragile: false,
        featured: true
      },
      {
        name: 'Anker MagGo Magnetic Wireless Power Bank (10,000mAh)',
        sku: 'PRD-US-TEC-19',
        category: catTech._id,
        description: '15W Qi2 certified fast wireless charging battery pack with built-in kickstand and smart LED display.',
        short_description: 'Anker MagGo 10000mAh MagSafe Power Bank.',
        price_coins: 37500,
        images: ['https://images.unsplash.com/photo-1609592424009-5407fa6d03d7?w=500'],
        stock: 70,
        weight_kg: 0.4,
        dimensions: { length_cm: 12, width_cm: 8, height_cm: 3 },
        package_type: 'box',
        fragile: false,
        featured: false
      },
      {
        name: 'Amazon Kindle Paperwhite 16GB (6.8" Paperwhite Display)',
        sku: 'PRD-US-TEC-20',
        category: catTech._id,
        description: 'Flush-front design, 300 ppi glare-free display, adjustable warm light, waterproof (IPX8), up to 10 weeks battery.',
        short_description: 'Amazon Kindle Paperwhite 16GB e-Reader.',
        price_coins: 41250,
        images: ['https://images.unsplash.com/photo-1592496431122-2349e0fbc666?w=500'],
        stock: 65,
        weight_kg: 0.3,
        dimensions: { length_cm: 18, width_cm: 13, height_cm: 2 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Ring Video Doorbell Pro 2 (1536p HD Head-to-Toe Video)',
        sku: 'PRD-US-TEC-21',
        category: catTech._id,
        description: 'Hardwired video doorbell with 3D Motion Detection, Bird\'s Eye View, Two-Way Talk, and night vision.',
        short_description: 'Ring Video Doorbell Pro 2 HD Security Camera.',
        price_coins: 45000,
        images: ['https://images.unsplash.com/photo-1558002038-1055907df827?w=500'],
        stock: 50,
        weight_kg: 0.5,
        dimensions: { length_cm: 15, width_cm: 8, height_cm: 5 },
        package_type: 'box',
        fragile: true,
        featured: false
      },
      {
        name: 'Google Nest Learning Thermostat 3rd Generation (Stainless)',
        sku: 'PRD-US-TEC-22',
        category: catTech._id,
        description: 'Auto-schedules based on your routine, remote app control, HVAC monitoring, energy history tracking.',
        short_description: 'Google Nest Smart Learning Thermostat.',
        price_coins: 48750,
        images: ['https://images.unsplash.com/photo-1567690187548-f07b1d7bf5a9?w=500'],
        stock: 45,
        weight_kg: 0.6,
        dimensions: { length_cm: 12, width_cm: 12, height_cm: 6 },
        package_type: 'box',
        fragile: true,
        featured: false
      },
      {
        name: 'Microsoft Xbox Series X 1TB Console (Black)',
        sku: 'PRD-US-TEC-25D',
        category: catTech._id,
        description: '12 Teraflops processing power, 4K gaming at up to 120 FPS, 3D Spatial Audio, Xbox Velocity Architecture.',
        short_description: 'Microsoft Xbox Series X 1TB Gaming Console.',
        price_coins: 142500,
        images: ['https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=500'],
        stock: 30,
        weight_kg: 4.5,
        dimensions: { length_cm: 30, width_cm: 15, height_cm: 15 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Apple iPad Air 11-inch M2 Wi-Fi 128GB (Space Gray)',
        sku: 'PRD-US-TEC-25E',
        category: catTech._id,
        description: 'Liquid Retina display, M2 chip performance, landscape 12MP front camera, Wi-Fi 6E, USB-C.',
        short_description: 'Apple iPad Air 11" M2 Wi-Fi 128GB.',
        price_coins: 179000,
        images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500'],
        stock: 35,
        weight_kg: 0.6,
        dimensions: { length_cm: 25, width_cm: 18, height_cm: 3 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Apple Watch Ultra 2 GPS + Cellular 49mm Titanium Case',
        sku: 'PRD-US-TEC-25F',
        category: catTech._id,
        description: 'Robust titanium case, S9 SiP chip, 3000 nits display brightness, precision dual-frequency GPS, 36-hour battery.',
        short_description: 'Apple Watch Ultra 2 49mm Titanium.',
        price_coins: 225000,
        images: ['https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=500'],
        stock: 25,
        weight_kg: 0.5,
        dimensions: { length_cm: 12, width_cm: 12, height_cm: 8 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Samsung Galaxy S24 Ultra 512GB Unlocked AI Smartphone',
        sku: 'PRD-US-TEC-25G',
        category: catTech._id,
        description: 'Snapdragon 8 Gen 3 for Galaxy, Galaxy AI Live Translate, 200MP quad camera, S Pen included, Titanium frame.',
        short_description: 'Samsung Galaxy S24 Ultra 512GB Unlocked.',
        price_coins: 285000,
        images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=500'],
        stock: 20,
        weight_kg: 0.5,
        dimensions: { length_cm: 18, width_cm: 10, height_cm: 5 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Apple MacBook Pro 16" M3 Max 36GB RAM 1TB SSD',
        sku: 'PRD-US-TEC-25H',
        category: catTech._id,
        description: '16-core CPU, 40-core GPU, Liquid Retina XDR display, up to 22 hours battery, Space Black aluminum unibody.',
        short_description: 'Apple MacBook Pro 16" M3 Max Space Black.',
        price_coins: 750000,
        images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500'],
        stock: 12,
        weight_kg: 2.2,
        dimensions: { length_cm: 36, width_cm: 25, height_cm: 4 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Pandora Moments Sterling Silver Barrel Clasp Charm Bracelet',
        sku: 'PRD-JWL-28',
        category: catJewelry._id,
        description: 'Hand-finished sterling silver snake chain bracelet with signature barrel clasp and 2 decorative charms.',
        short_description: 'Pandora Sterling Silver Charm Bracelet.',
        price_coins: 22500,
        images: ['https://images.unsplash.com/photo-1611591475777-233ca73222d3?w=500'],
        stock: 60,
        weight_kg: 0.2,
        dimensions: { length_cm: 10, width_cm: 10, height_cm: 4 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: '14K White Gold Round Diamond Stud Earrings (0.5 Carat)',
        sku: 'PRD-JWL-29',
        category: catJewelry._id,
        description: 'Pair of classic 14K white gold 4-prong stud earrings with 0.50 ct total weight round brilliant cut diamonds.',
        short_description: '14K Gold 0.5 Carat Diamond Stud Earrings.',
        price_coins: 37500,
        images: ['https://images.unsplash.com/photo-1630019852942-f89202989a59?w=500'],
        stock: 45,
        weight_kg: 0.1,
        dimensions: { length_cm: 8, width_cm: 8, height_cm: 4 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Cartier Love Bracelet 18K Yellow Gold',
        sku: 'PRD-JWL-30C',
        category: catJewelry._id,
        description: 'Iconic 18K yellow gold oval bangle composed of two rigid arcs bound together with a screwdriver.',
        short_description: 'Cartier Love Bracelet 18K Yellow Gold.',
        price_coins: 320000,
        images: ['https://images.unsplash.com/photo-1611591475777-233ca73222d3?w=500'],
        stock: 15,
        weight_kg: 0.3,
        dimensions: { length_cm: 12, width_cm: 12, height_cm: 6 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Yves Saint Laurent Black Opium Eau de Parfum (90ml)',
        sku: 'PRD-PRF-33',
        category: catPerfumes._id,
        description: 'Seductively intoxicating warm and spicy fragrance featuring coffee, vanilla, and white flowers.',
        short_description: 'YSL Black Opium Eau de Parfum 90ml.',
        price_coins: 33750,
        images: ['https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=500'],
        stock: 70,
        weight_kg: 0.5,
        dimensions: { length_cm: 14, width_cm: 10, height_cm: 6 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Chanel Coco Mademoiselle Intense Eau de Parfum (100ml)',
        sku: 'PRD-PRF-35',
        category: catPerfumes._id,
        description: 'Oriental woody and amber fragrance with an extreme character, centered around patchouli and tonka bean.',
        short_description: 'Chanel Coco Mademoiselle Intense 100ml.',
        price_coins: 45000,
        images: ['https://images.unsplash.com/photo-1541643600914-78b084683601?w=500'],
        stock: 50,
        weight_kg: 0.5,
        dimensions: { length_cm: 15, width_cm: 10, height_cm: 6 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Tom Ford Tobacco Vanille Eau de Parfum Spray (50ml)',
        sku: 'PRD-PRF-36',
        category: catPerfumes._id,
        description: 'Opulent, warm, and iconic fragrance featuring tobacco leaf, spices, vanilla, cocoa, and sweet wood sap.',
        short_description: 'Tom Ford Tobacco Vanille EDP 50ml.',
        price_coins: 78000,
        images: ['https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=500'],
        stock: 40,
        weight_kg: 0.4,
        dimensions: { length_cm: 12, width_cm: 8, height_cm: 6 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Luxury Leather Handbag & Matching Zip Clutch Bag Set',
        sku: 'PRD-US-FAS-43B',
        category: catBeauty._id,
        description: 'Premium pebbled Italian leather tote bag with gold-tone hardware and matching zip clutch bag.',
        short_description: 'Luxury Leather Handbag & Matching Clutch Set.',
        price_coins: 59250,
        images: ['https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=500'],
        stock: 50,
        weight_kg: 1.1,
        dimensions: { length_cm: 35, width_cm: 28, height_cm: 14 },
        package_type: 'box',
        fragile: false,
        featured: true
      },
      {
        name: 'Levi\'s 501 Original Fit Mens Denim Jeans',
        sku: 'PRD-US-FAS-43C',
        category: catBeauty._id,
        description: 'The original straight leg button fly denim jeans in authentic dark indigo blue wash.',
        short_description: 'Levi\'s 501 Original Fit Mens Denim Jeans.',
        price_coins: 66000,
        images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500'],
        stock: 65,
        weight_kg: 0.8,
        dimensions: { length_cm: 30, width_cm: 25, height_cm: 6 },
        package_type: 'box',
        fragile: false,
        featured: false
      },
      {
        name: 'Lululemon Align High-Rise 25" Yoga Leggings',
        sku: 'PRD-US-FAS-43D',
        category: catBeauty._id,
        description: 'Ultra-soft Nulu fabric feels weightless, four-way stretch, sweat-wicking for workouts and casual wear.',
        short_description: 'Lululemon Align High-Rise Yoga Leggings.',
        price_coins: 73500,
        images: ['https://images.unsplash.com/photo-1506152983158-b4a74a01c721?w=500'],
        stock: 60,
        weight_kg: 0.3,
        dimensions: { length_cm: 25, width_cm: 20, height_cm: 4 },
        package_type: 'box',
        fragile: false,
        featured: true
      },
      {
        name: 'The North Face Antora Waterproof Hooded Rain Jacket',
        sku: 'PRD-US-FAS-43G',
        category: catBeauty._id,
        description: 'DryVent 2L waterproof, breathable, seam-sealed shell with 100% recycled nylon and adjustable hood.',
        short_description: 'The North Face Antora Waterproof Rain Jacket.',
        price_coins: 82500,
        images: ['https://images.unsplash.com/photo-1544441893-675973e31985?w=500'],
        stock: 45,
        weight_kg: 0.6,
        dimensions: { length_cm: 30, width_cm: 25, height_cm: 6 },
        package_type: 'box',
        fragile: false,
        featured: false
      },
      {
        name: 'Timberland 6-Inch Premium Waterproof Mens Boots',
        sku: 'PRD-US-FAS-43H',
        category: catBeauty._id,
        description: 'Iconic wheat nubuck leather waterproof boots with 400g PrimaLoft insulation and anti-fatigue footbeds.',
        short_description: 'Timberland 6-Inch Premium Waterproof Boots.',
        price_coins: 157500,
        images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500'],
        stock: 40,
        weight_kg: 1.8,
        dimensions: { length_cm: 35, width_cm: 25, height_cm: 15 },
        package_type: 'box',
        fragile: false,
        featured: true
      },
      {
        name: 'Gucci GG Marmont Matelassé Leather Shoulder Bag',
        sku: 'PRD-US-FAS-43I',
        category: catBeauty._id,
        description: 'Crafted from black chevron matelassé leather with Double G antique gold hardware and sliding chain strap.',
        short_description: 'Gucci GG Marmont Matelassé Leather Bag.',
        price_coins: 420000,
        images: ['https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=500'],
        stock: 15,
        weight_kg: 1.0,
        dimensions: { length_cm: 30, width_cm: 20, height_cm: 10 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Naija Crunchy Spicy Plantain Chips & Chin Chin Box',
        sku: 'PRD-GRO-46B',
        category: catFood._id,
        description: 'Assorted West African snacks including spicy plantain chips, crunchy sweet chin chin, and salted peanuts.',
        short_description: 'Naija Crunchy Snacks Variety Box.',
        price_coins: 21375,
        images: ['https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=500'],
        stock: 90,
        weight_kg: 1.5,
        dimensions: { length_cm: 30, width_cm: 20, height_cm: 12 },
        package_type: 'box',
        fragile: false,
        featured: true
      },
      {
        name: 'Egusi & Ogbono Soup Ingredients Super Family Pack',
        sku: 'PRD-GRO-46C',
        category: catFood._id,
        description: 'Ground melon seeds (Egusi), wild mango seeds (Ogbono), dried crayfish, stockfish flakes & pepper mix.',
        short_description: 'Egusi & Ogbono Soup Ingredients Pack.',
        price_coins: 25125,
        images: ['https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500'],
        stock: 70,
        weight_kg: 2.5,
        dimensions: { length_cm: 35, width_cm: 25, height_cm: 15 },
        package_type: 'box',
        fragile: false,
        featured: true
      },
      {
        name: 'California Organic Extra Virgin Olive Oil (3 Liters)',
        sku: 'PRD-GRO-46D',
        category: catFood._id,
        description: 'First cold pressed organic extra virgin olive oil harvested from California estate olive groves.',
        short_description: 'California Organic Extra Virgin Olive Oil 3L.',
        price_coins: 28500,
        images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500'],
        stock: 65,
        weight_kg: 3.2,
        dimensions: { length_cm: 30, width_cm: 15, height_cm: 15 },
        package_type: 'box',
        fragile: true,
        featured: false
      },
      {
        name: 'Customized Printed Throw Pillow (Set of 2)',
        sku: 'PRD-HOM-48',
        category: catHome._id,
        description: 'Soft linen throw pillows printed with custom family photos or anniversary dates.',
        short_description: 'Customized Printed Throw Pillow Set.',
        price_coins: 14250,
        images: ['https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=500'],
        stock: 80,
        weight_kg: 0.8,
        dimensions: { length_cm: 45, width_cm: 45, height_cm: 15 },
        package_type: 'box',
        fragile: false,
        featured: false
      },
      {
        name: 'Luxury Scented Soy Candles Gift Box (Set of 3)',
        sku: 'PRD-HOM-50',
        category: catHome._id,
        description: 'Hand-poured 100% natural soy wax candles with lavender, vanilla, and eucalyptus essential oil scents.',
        short_description: 'Luxury Scented Soy Candles Box (3 Set).',
        price_coins: 16875,
        images: ['https://images.unsplash.com/photo-1603006905003-be475563bc59?w=500'],
        stock: 75,
        weight_kg: 1.1,
        dimensions: { length_cm: 25, width_cm: 10, height_cm: 10 },
        package_type: 'box',
        fragile: true,
        featured: false
      },
      {
        name: 'Nespresso Vertuo Pop+ Coffee & Espresso Machine',
        sku: 'PRD-HOM-50B',
        category: catHome._id,
        description: 'Compact pod coffee maker with Centrifusion extraction technology for barista-grade crema and coffee.',
        short_description: 'Nespresso Vertuo Pop+ Espresso Machine.',
        price_coins: 37500,
        images: ['https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=500'],
        stock: 50,
        weight_kg: 3.5,
        dimensions: { length_cm: 30, width_cm: 20, height_cm: 25 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Dyson V8 Cordless Vacuum Cleaner (Nickel/Cobalt)',
        sku: 'PRD-HOM-50C',
        category: catHome._id,
        description: 'Lightweight cordless stick vacuum with de-tangling Motorbar cleaner head, up to 40 minutes run time.',
        short_description: 'Dyson V8 Cordless Vacuum Cleaner.',
        price_coins: 98000,
        images: ['https://images.unsplash.com/photo-1558317374-067fb5f30001?w=500'],
        stock: 30,
        weight_kg: 2.6,
        dimensions: { length_cm: 125, width_cm: 25, height_cm: 22 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Armor All Ultimate 8-Piece Car Wash Bucket Kit',
        sku: 'PRD-US-AUT-52',
        category: catAuto._id,
        description: 'Includes Ultra Shinning Car Wash & Wax, Tire Foam Protectant, Glass Wipes, Microfiber Towel, and Wash Mitt.',
        short_description: 'Armor All 8-Piece Car Wash Kit.',
        price_coins: 22500,
        images: ['https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?w=500'],
        stock: 70,
        weight_kg: 3.5,
        dimensions: { length_cm: 30, width_cm: 25, height_cm: 25 },
        package_type: 'box',
        fragile: false,
        featured: false
      },
      {
        name: 'NOCO Boost Plus GB40 1000A 12V UltraSafe Lithium Jump Starter',
        sku: 'PRD-US-AUT-53',
        category: catAuto._id,
        description: 'Safely jump start a dead battery in seconds. Rated for gasoline engines up to 6 liters and diesel engines up to 3 liters.',
        short_description: 'NOCO GB40 1000A Lithium Car Jump Starter.',
        price_coins: 61500,
        images: ['https://images.unsplash.com/photo-1563720223185-11003d516935?w=500'],
        stock: 55,
        weight_kg: 1.2,
        dimensions: { length_cm: 20, width_cm: 12, height_cm: 8 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'WeatherTech Custom-Fit All-Weather Car FloorMat Set',
        sku: 'PRD-US-AUT-53B',
        category: catAuto._id,
        description: 'Laser measured front and rear floor liners engineered to protect carpeted vehicle interiors from mud, snow, and spills.',
        short_description: 'WeatherTech Custom-Fit Car FloorMat Set.',
        price_coins: 75000,
        images: ['https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?w=500'],
        stock: 45,
        weight_kg: 4.0,
        dimensions: { length_cm: 75, width_cm: 55, height_cm: 15 },
        package_type: 'box',
        fragile: false,
        featured: false
      },
      {
        name: 'Garmin Dash Cam 57 1440p Quad HD Driving Recorder',
        sku: 'PRD-US-AUT-54',
        category: catAuto._id,
        description: 'Wide 140-degree field of view captures clear 1440p HD video. Voice control, incident detection, and live view monitoring.',
        short_description: 'Garmin Dash Cam 57 Quad HD Driving Camera.',
        price_coins: 111000,
        images: ['https://images.unsplash.com/photo-1558002038-1055907df827?w=500'],
        stock: 40,
        weight_kg: 0.5,
        dimensions: { length_cm: 12, width_cm: 10, height_cm: 6 },
        package_type: 'box',
        fragile: true,
        featured: false
      }
`;

// Insert additional products into Product.create([ ... ]) block
content = content.replace('      // --- 9. AUTOMOTIVE & VEHICLES ---', `${additionalProductsCode}\n      // --- 9. AUTOMOTIVE & VEHICLES ---`);

fs.writeFileSync(seedFilePath, content, 'utf8');
console.log('Successfully updated seed.js with additional 60+ products!');
