const fs = require('fs');
const path = require('path');

const seedPath = path.join(__dirname, './seed.js');
let seedContent = fs.readFileSync(seedPath, 'utf8');

const new48ProductsCode = `
      // --- NEW 48 REAL-LIFE PRODUCTS (TOTAL catalog = 129 items) ---
      {
        name: 'Papa John\'s Epic Stuffed Crust Cheese Pizza (14")',
        sku: 'PRD-FF-13',
        category: catFastFood._id,
        description: 'Original hand-tossed dough stuffed with real mozzarella cheese, signature tomato sauce, and 100% real cheese blend.',
        short_description: 'Papa John\'s 14" Stuffed Crust Pizza.',
        price_coins: 20250,
        images: ['https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=500'],
        stock: 80,
        weight_kg: 1.8,
        dimensions: { length_cm: 36, width_cm: 36, height_cm: 10 },
        package_type: 'box',
        fragile: false,
        featured: true
      },
      {
        name: 'Wendy\'s Baconator & Large Chocolate Frosty Shake Combo',
        sku: 'PRD-FF-14',
        category: catFastFood._id,
        description: 'Half-pound of fresh beef, six strips of crispy smoked bacon, American cheese, ketchup, mayo, with thick Frosty shake.',
        short_description: 'Wendy\'s Baconator & Frosty Shake Combo.',
        price_coins: 21000,
        images: ['https://images.unsplash.com/photo-1550547660-d9450f859349?w=500'],
        stock: 75,
        weight_kg: 1.4,
        dimensions: { length_cm: 25, width_cm: 20, height_cm: 12 },
        package_type: 'box',
        fragile: false,
        featured: true
      },
      {
        name: 'Panda Express Orange Chicken & Fried Rice Family Plate',
        sku: 'PRD-FF-15',
        category: catFastFood._id,
        description: 'Crispy boneless chicken bites tossed in sweet & spicy orange sauce over wok-fried egg rice and veggies.',
        short_description: 'Panda Express Orange Chicken & Fried Rice.',
        price_coins: 21750,
        images: ['https://images.unsplash.com/photo-1525755662778-989d0524087e?w=500'],
        stock: 85,
        weight_kg: 1.5,
        dimensions: { length_cm: 28, width_cm: 22, height_cm: 10 },
        package_type: 'box',
        fragile: false,
        featured: false
      },
      {
        name: 'Subway Footlong Italian B.M.T. Sub Sandwich',
        sku: 'PRD-FF-16',
        category: catFastFood._id,
        description: 'Genoa salami, spicy pepperoni, Black Forest ham on toasted Parmesan Oregano bread with fresh lettuce, tomatoes & mayo.',
        short_description: 'Subway Footlong Italian B.M.T. Sub.',
        price_coins: 22500,
        images: ['https://images.unsplash.com/photo-1509722747041-616f39b57569?w=500'],
        stock: 90,
        weight_kg: 0.9,
        dimensions: { length_cm: 32, width_cm: 12, height_cm: 8 },
        package_type: 'box',
        fragile: false,
        featured: true
      },
      {
        name: 'Starbucks Iced Caramel Macchiato & Chocolate Chip Muffin',
        sku: 'PRD-FF-17',
        category: catFastFood._id,
        description: 'Freshly brewed espresso with vanilla syrup, milk, ice, and buttery caramel drizzle served with rich chocolate chip muffin.',
        short_description: 'Starbucks Iced Caramel Macchiato & Muffin.',
        price_coins: 23250,
        images: ['https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=500'],
        stock: 95,
        weight_kg: 0.8,
        dimensions: { length_cm: 20, width_cm: 15, height_cm: 15 },
        package_type: 'box',
        fragile: false,
        featured: true
      },
      {
        name: 'Texas Roadhouse USDA Choice 12oz Ribeye Steak Meal',
        sku: 'PRD-FF-18',
        category: catFastFood._id,
        description: '12oz hand-cut juicy USDA choice ribeye steak grilled over open flame with loaded baked potato and fresh rolls.',
        short_description: 'Texas Roadhouse 12oz Ribeye Steak Meal.',
        price_coins: 24000,
        images: ['https://images.unsplash.com/photo-1544025162-d76694265947?w=500'],
        stock: 60,
        weight_kg: 1.6,
        dimensions: { length_cm: 28, width_cm: 22, height_cm: 10 },
        package_type: 'box',
        fragile: false,
        featured: true
      },

      // Family Gift Boxes (+5)
      {
        name: 'Burt\'s Bees Natural Everyday Essential Body Care Gift Set',
        sku: 'PRD-GIF-17',
        category: catGifts._id,
        description: 'Includes Beeswax Lip Balm, Deep Cleansing Cream, Hand Salve, Body Lotion, and Coconut Foot Cream.',
        short_description: 'Burt\'s Bees Natural Everyday Gift Set.',
        price_coins: 24750,
        images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500'],
        stock: 75,
        weight_kg: 0.8,
        dimensions: { length_cm: 22, width_cm: 18, height_cm: 8 },
        package_type: 'box',
        fragile: false,
        featured: false
      },
      {
        name: 'Godiva Belgian Dark Chocolate Truffles Gift Box (24 Pc)',
        sku: 'PRD-GIF-18',
        category: catGifts._id,
        description: 'Decadent dark chocolate truffles filled with double dark ganache, salted caramel, and Aztec spice.',
        short_description: 'Godiva Belgian Dark Truffles Box (24 pc).',
        price_coins: 27000,
        images: ['https://images.unsplash.com/photo-1548907040-4baa42d10919?w=500'],
        stock: 65,
        weight_kg: 0.7,
        dimensions: { length_cm: 25, width_cm: 18, height_cm: 5 },
        package_type: 'box',
        fragile: false,
        featured: true
      },
      {
        name: 'Gourmet Fruit & Artisan Cheese Wooden Crate Gift Basket',
        sku: 'PRD-GIF-19',
        category: catGifts._id,
        description: 'Fresh Fuji apples, D\'Anjou pears, sharp cheddar cheese, dried cranberries, and roasted almonds in a wooden crate.',
        short_description: 'Gourmet Fruit & Cheese Wooden Crate Basket.',
        price_coins: 33000,
        images: ['https://images.unsplash.com/photo-1567306301408-9b74779a11af?w=500'],
        stock: 50,
        weight_kg: 3.2,
        dimensions: { length_cm: 36, width_cm: 28, height_cm: 16 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Custom Engraved Glass Photo Frame & Lavender Candle Set',
        sku: 'PRD-GIF-20',
        category: catGifts._id,
        description: 'Personalized 8x10 glass frame engraved with family names paired with hand-poured soy lavender candle.',
        short_description: 'Custom Glass Frame & Candle Gift Set.',
        price_coins: 36000,
        images: ['https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=500'],
        stock: 55,
        weight_kg: 1.5,
        dimensions: { length_cm: 28, width_cm: 22, height_cm: 12 },
        package_type: 'box',
        fragile: true,
        featured: false
      },
      {
        name: 'Starbucks Coffee Beans & Stainless Thermal Tumbler Basket',
        sku: 'PRD-GIF-21',
        category: catGifts._id,
        description: 'Two 12oz Starbucks roast coffee bags, double-wall stainless travel tumbler, and dark chocolate bars.',
        short_description: 'Starbucks Coffee & Tumbler Gift Basket.',
        price_coins: 39000,
        images: ['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500'],
        stock: 60,
        weight_kg: 2.1,
        dimensions: { length_cm: 32, width_cm: 25, height_cm: 14 },
        package_type: 'box',
        fragile: false,
        featured: true
      },

      // Electronics & Tech (+8)
      {
        name: 'Apple MagSafe Battery Pack White for iPhone',
        sku: 'PRD-US-TEC-25I',
        category: catTech._id,
        description: 'Compact magnetic wireless charging battery pack seamlessly attaches to iPhone 12, 13, 14 & 15 models.',
        short_description: 'Apple MagSafe Battery Pack White.',
        price_coins: 42000,
        images: ['https://images.unsplash.com/photo-1609592424009-5407fa6d03d7?w=500'],
        stock: 80,
        weight_kg: 0.3,
        dimensions: { length_cm: 10, width_cm: 8, height_cm: 3 },
        package_type: 'box',
        fragile: false,
        featured: false
      },
      {
        name: 'JBL Flip 6 Waterproof Portable Bluetooth Speaker',
        sku: 'PRD-US-TEC-25J',
        category: catTech._id,
        description: '2-way speaker system delivers loud, crystal clear, powerful sound. IP67 waterproof and 12 hours battery.',
        short_description: 'JBL Flip 6 Waterproof Bluetooth Speaker.',
        price_coins: 45000,
        images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?w=500'],
        stock: 75,
        weight_kg: 0.6,
        dimensions: { length_cm: 18, width_cm: 8, height_cm: 8 },
        package_type: 'box',
        fragile: false,
        featured: true
      },
      {
        name: 'Razer BlackWidow V4 Pro Mechanical Gaming Keyboard',
        sku: 'PRD-US-TEC-25K',
        category: catTech._id,
        description: 'Chroma RGB per-key lighting, mechanical green clicky switches, command dial, 8 dedicated macro keys.',
        short_description: 'Razer BlackWidow V4 Pro Mechanical Keyboard.',
        price_coins: 67500,
        images: ['https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500'],
        stock: 45,
        weight_kg: 1.4,
        dimensions: { length_cm: 46, width_cm: 16, height_cm: 5 },
        package_type: 'box',
        fragile: true,
        featured: false
      },
      {
        name: 'Samsung T7 Shield 2TB Portable External SSD (Black)',
        sku: 'PRD-US-TEC-25L',
        category: catTech._id,
        description: 'Superfast read speeds up to 1050 MB/s, rugged IP65 water and dust resistant rubberized shell.',
        short_description: 'Samsung T7 Shield 2TB Portable SSD.',
        price_coins: 72000,
        images: ['https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=500'],
        stock: 50,
        weight_kg: 0.2,
        dimensions: { length_cm: 9, width_cm: 6, height_cm: 2 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'GoPro HERO12 Black Waterproof 5.3K Action Camera',
        sku: 'PRD-US-TEC-25M',
        category: catTech._id,
        description: '5.3K60 video recording, HyperSmooth 6.0 stabilization, HDR photos, waterproof down to 33ft (10m).',
        short_description: 'GoPro HERO12 Black 5.3K Action Camera.',
        price_coins: 145000,
        images: ['https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=500'],
        stock: 35,
        weight_kg: 0.4,
        dimensions: { length_cm: 12, width_cm: 10, height_cm: 6 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'DJI Mini 4 Pro Fly More Combo Drone Camera (RC 2)',
        sku: 'PRD-US-TEC-25N',
        category: catTech._id,
        description: 'Under 249g ultra-light, 4K/60fps HDR video, omnidirectional obstacle sensing, 34-min flight time per battery.',
        short_description: 'DJI Mini 4 Pro Fly More Drone Camera.',
        price_coins: 260000,
        images: ['https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=500'],
        stock: 20,
        weight_kg: 1.8,
        dimensions: { length_cm: 30, width_cm: 25, height_cm: 15 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Canon EOS R6 Mark II Mirrorless Camera Body',
        sku: 'PRD-US-TEC-25O',
        category: catTech._id,
        description: '24.2 MP full-frame CMOS sensor, 40 fps electronic shutter, 4K60p uncropped video, Dual Pixel CMOS AF II.',
        short_description: 'Canon EOS R6 Mark II Mirrorless Camera Body.',
        price_coins: 680000,
        images: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500'],
        stock: 15,
        weight_kg: 1.2,
        dimensions: { length_cm: 20, width_cm: 15, height_cm: 12 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'LG C3 65-inch 4K Smart OLED TV 120Hz (OLED65C3PSA)',
        sku: 'PRD-US-TEC-25P',
        category: catTech._id,
        description: 'Self-lit OLED pixels, α9 AI Processor Gen6, Dolby Vision & Atmos, 0.1ms response time, 4x HDMI 2.1 ports.',
        short_description: 'LG C3 65-inch 4K Smart OLED TV 120Hz.',
        price_coins: 720000,
        images: ['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500'],
        stock: 10,
        weight_kg: 22.0,
        dimensions: { length_cm: 145, width_cm: 85, height_cm: 15 },
        package_type: 'box',
        fragile: true,
        featured: true
      },

      // Jewelry & Fine Accessories (+5)
      {
        name: '10K Solid Yellow Gold Franco Chain Necklace (22 Inch)',
        sku: 'PRD-JWL-30D',
        category: catJewelry._id,
        description: '2.5mm solid 10K yellow gold Franco link chain with lobster claw clasp. Polished mirror finish.',
        short_description: '10K Solid Gold Franco Chain 22".',
        price_coins: 49500,
        images: ['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500'],
        stock: 45,
        weight_kg: 0.3,
        dimensions: { length_cm: 12, width_cm: 10, height_cm: 4 },
        package_type: 'box',
        fragile: true,
        featured: false
      },
      {
        name: 'Swarovski Crystal Tennis Bracelet Rhodium Plated',
        sku: 'PRD-JWL-30E',
        category: catJewelry._id,
        description: 'Classic round clear Swarovski crystals set in rhodium-plated prongs with fold-over safety clasp.',
        short_description: 'Swarovski Crystal Tennis Bracelet.',
        price_coins: 52500,
        images: ['https://images.unsplash.com/photo-1611591475777-233ca73222d3?w=500'],
        stock: 50,
        weight_kg: 0.2,
        dimensions: { length_cm: 10, width_cm: 10, height_cm: 4 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: '14K Yellow Gold Classic Hoop Earrings (30mm)',
        sku: 'PRD-JWL-30F',
        category: catJewelry._id,
        description: 'Lightweight 14K solid yellow gold round polished hoops with secure snap-down latch closure.',
        short_description: '14K Gold Classic 30mm Hoop Earrings.',
        price_coins: 58500,
        images: ['https://images.unsplash.com/photo-1630019852942-f89202989a59?w=500'],
        stock: 40,
        weight_kg: 0.2,
        dimensions: { length_cm: 10, width_cm: 10, height_cm: 4 },
        package_type: 'box',
        fragile: true,
        featured: false
      },
      {
        name: 'Custom Moissanite Iced Out Medallion Pendant Necklace',
        sku: 'PRD-JWL-30G',
        category: catJewelry._id,
        description: 'VVS D-Color moissanite stones set in 925 sterling silver plated in 14K gold. Passes diamond tester.',
        short_description: 'Iced Out Moissanite Medallion Pendant.',
        price_coins: 95000,
        images: ['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500'],
        stock: 30,
        weight_kg: 0.4,
        dimensions: { length_cm: 14, width_cm: 12, height_cm: 5 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Rolex Datejust 41mm Two-Tone Gold & Steel Watch',
        sku: 'PRD-JWL-30H',
        category: catJewelry._id,
        description: '18K yellow gold fluted bezel, champagne dial, Jubilee bracelet in Oystersteel and yellow gold.',
        short_description: 'Rolex Datejust 41mm Two-Tone Gold Watch.',
        price_coins: 520000,
        images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500'],
        stock: 8,
        weight_kg: 0.9,
        dimensions: { length_cm: 15, width_cm: 15, height_cm: 10 },
        package_type: 'box',
        fragile: true,
        featured: true
      },

      // Perfumes (+5)
      {
        name: 'Versace Eros Eau de Toilette Spray (100ml)',
        sku: 'PRD-PRF-38B',
        category: catPerfumes._id,
        description: 'Luminous aura with intense mint leaves, Italian lemon zest, green apple, tonka bean, and cedarwood.',
        short_description: 'Versace Eros Eau de Toilette Spray 100ml.',
        price_coins: 31500,
        images: ['https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=500'],
        stock: 75,
        weight_kg: 0.5,
        dimensions: { length_cm: 14, width_cm: 10, height_cm: 6 },
        package_type: 'box',
        fragile: true,
        featured: false
      },
      {
        name: 'Paco Rabanne 1 Million Eau de Toilette (100ml)',
        sku: 'PRD-PRF-38C',
        category: catPerfumes._id,
        description: 'Spicy leather fragrance with notes of blood mandarin, cinnamon, rose, leather accord, and amber ketal.',
        short_description: 'Paco Rabanne 1 Million EDT 100ml.',
        price_coins: 34500,
        images: ['https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=500'],
        stock: 70,
        weight_kg: 0.5,
        dimensions: { length_cm: 14, width_cm: 10, height_cm: 6 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Yves Saint Laurent Y Eau de Parfum Spray (100ml)',
        sku: 'PRD-PRF-38D',
        category: catPerfumes._id,
        description: 'Bold woody aromatic fragrance blending crisp apple, sage, vetiver, and sensual tonka bean.',
        short_description: 'YSL Y Eau de Parfum Spray 100ml.',
        price_coins: 42000,
        images: ['https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=500'],
        stock: 60,
        weight_kg: 0.5,
        dimensions: { length_cm: 14, width_cm: 10, height_cm: 6 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Parfums de Marly Layton Eau de Parfum (125ml)',
        sku: 'PRD-PRF-38E',
        category: catPerfumes._id,
        description: 'Distinguished oriental floral fragrance with apple, lavender, vanilla, pepper, and noble wood notes.',
        short_description: 'Parfums de Marly Layton EDP 125ml.',
        price_coins: 105000,
        images: ['https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=500'],
        stock: 35,
        weight_kg: 0.7,
        dimensions: { length_cm: 16, width_cm: 12, height_cm: 8 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Louis Vuitton Ombre Nomade Eau de Parfum (100ml)',
        sku: 'PRD-PRF-38F',
        category: catPerfumes._id,
        description: 'Exclusive luxury oud fragrance with rare natural agarwood, raspberry, incense, and rose centifolia.',
        short_description: 'Louis Vuitton Ombre Nomade EDP 100ml.',
        price_coins: 145000,
        images: ['https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=500'],
        stock: 25,
        weight_kg: 0.7,
        dimensions: { length_cm: 16, width_cm: 12, height_cm: 8 },
        package_type: 'box',
        fragile: true,
        featured: true
      },

      // Beauty & Fashion (+6)
      {
        name: 'Nike Sportswear Club Fleece Pullover Hoodie (Black)',
        sku: 'PRD-US-FAS-43J',
        category: catBeauty._id,
        description: 'Brushed-back fleece fabric is soft and smooth, ribbed hem and cuffs, kangaroo pocket with embroidered Futura logo.',
        short_description: 'Nike Club Fleece Pullover Hoodie.',
        price_coins: 28500,
        images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=500'],
        stock: 85,
        weight_kg: 0.7,
        dimensions: { length_cm: 30, width_cm: 25, height_cm: 8 },
        package_type: 'box',
        fragile: false,
        featured: false
      },
      {
        name: 'Adidas Originals Samba OG White Black Gum Sneakers',
        sku: 'PRD-US-FAS-43K',
        category: catBeauty._id,
        description: 'Full grain leather upper with gritty suede overlay, serrated 3-Stripes, and gum rubber outsole.',
        short_description: 'Adidas Originals Samba OG Sneakers.',
        price_coins: 43500,
        images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=500'],
        stock: 70,
        weight_kg: 1.2,
        dimensions: { length_cm: 32, width_cm: 22, height_cm: 12 },
        package_type: 'box',
        fragile: false,
        featured: true
      },
      {
        name: 'Ugg Classic Short II Chestnut Sheepskin Boots',
        sku: 'PRD-US-FAS-43L',
        category: catBeauty._id,
        description: 'Twinface sheepskin pretreated to repel moisture and stains, Treadlite by UGG outsole for traction.',
        short_description: 'Ugg Classic Short II Chestnut Boots.',
        price_coins: 86000,
        images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500'],
        stock: 50,
        weight_kg: 1.4,
        dimensions: { length_cm: 34, width_cm: 24, height_cm: 14 },
        package_type: 'box',
        fragile: false,
        featured: true
      },
      {
        name: 'Oakley Holbrook Matte Black Polarized Sport Sunglasses',
        sku: 'PRD-US-FAS-43M',
        category: catBeauty._id,
        description: 'O Matter frame material, Prizm Black Polarized lenses enhance color, contrast, and detail for outdoors.',
        short_description: 'Oakley Holbrook Polarized Sunglasses.',
        price_coins: 92000,
        images: ['https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500'],
        stock: 45,
        weight_kg: 0.3,
        dimensions: { length_cm: 18, width_cm: 8, height_cm: 6 },
        package_type: 'box',
        fragile: true,
        featured: false
      },
      {
        name: 'Canada Goose Expedition Parka Down Jacket (Black)',
        sku: 'PRD-US-FAS-43N',
        category: catBeauty._id,
        description: '625 fill power white duck down insulation, Arctic Tech fabric, fleece-lined handwarmer pockets, rated for -30°C.',
        short_description: 'Canada Goose Expedition Down Parka Jacket.',
        price_coins: 380000,
        images: ['https://images.unsplash.com/photo-1544441893-675973e31985?w=500'],
        stock: 20,
        weight_kg: 2.5,
        dimensions: { length_cm: 45, width_cm: 35, height_cm: 15 },
        package_type: 'box',
        fragile: false,
        featured: true
      },
      {
        name: 'Louis Vuitton Neverfull MM Damier Ebene Tote Bag',
        sku: 'PRD-US-FAS-43O',
        category: catBeauty._id,
        description: 'Damier Ebene coated canvas with natural cowhide leather trim, red striped textile lining, and removable pouch.',
        short_description: 'Louis Vuitton Neverfull MM Tote Bag.',
        price_coins: 490000,
        images: ['https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=500'],
        stock: 12,
        weight_kg: 1.2,
        dimensions: { length_cm: 40, width_cm: 30, height_cm: 15 },
        package_type: 'box',
        fragile: true,
        featured: true
      },

      // Food & Groceries (+4)
      {
        name: 'Ghirardelli Premium Baking Unsweetened Cocoa Powder (8 oz)',
        sku: 'PRD-GRO-46E',
        category: catFood._id,
        description: '100% unsweetened cocoa powder made from high quality roasted cocoa beans for cakes, brownies, and hot chocolate.',
        short_description: 'Ghirardelli Premium Baking Cocoa 8 oz.',
        price_coins: 12750,
        images: ['https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=500'],
        stock: 90,
        weight_kg: 0.3,
        dimensions: { length_cm: 12, width_cm: 8, height_cm: 8 },
        package_type: 'box',
        fragile: false,
        featured: false
      },
      {
        name: 'McCormick Grill Mates BBQ Seasoning Variety Pack (4 Jars)',
        sku: 'PRD-GRO-46F',
        category: catFood._id,
        description: 'Includes Montreal Steak, Montreal Chicken, Garlic Herb & Wine, and Mesquite seasoning blends.',
        short_description: 'McCormick Grill Mates BBQ Seasoning 4-Pack.',
        price_coins: 14250,
        images: ['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500'],
        stock: 85,
        weight_kg: 0.8,
        dimensions: { length_cm: 20, width_cm: 15, height_cm: 10 },
        package_type: 'box',
        fragile: true,
        featured: false
      },
      {
        name: 'Bumble Bee Premium Solid White Albacore Tuna in Water (8 Pack)',
        sku: 'PRD-GRO-46G',
        category: catFood._id,
        description: 'Wild caught wild albacore tuna packed in water. High protein, non-GMO, gluten-free, 5 oz cans.',
        short_description: 'Bumble Bee Solid White Albacore Tuna 8-Pack.',
        price_coins: 16500,
        images: ['https://images.unsplash.com/photo-1584278860047-22db9f3788b6?w=500'],
        stock: 80,
        weight_kg: 1.6,
        dimensions: { length_cm: 25, width_cm: 15, height_cm: 10 },
        package_type: 'box',
        fragile: false,
        featured: false
      },
      {
        name: 'Filippo Berio Extra Virgin Olive Oil Tin (3 Liters)',
        sku: 'PRD-GRO-46H',
        category: catFood._id,
        description: 'Imported Italian extra virgin olive oil with well-balanced rich fruity flavor for dressings, marinades, and drizzling.',
        short_description: 'Filippo Berio Extra Virgin Olive Oil 3L Tin.',
        price_coins: 29500,
        images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500'],
        stock: 60,
        weight_kg: 3.2,
        dimensions: { length_cm: 30, width_cm: 15, height_cm: 15 },
        package_type: 'box',
        fragile: false,
        featured: true
      },

      // Home & Living (+5)
      {
        name: 'Bialetti Moka Express 6-Cup Stovetop Espresso Maker',
        sku: 'PRD-HOM-50D',
        category: catHome._id,
        description: 'Made in Italy polished aluminum stovetop espresso maker produces 6 cups of rich authentic Italian espresso.',
        short_description: 'Bialetti Moka Express 6-Cup Espresso Maker.',
        price_coins: 19500,
        images: ['https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=500'],
        stock: 70,
        weight_kg: 0.9,
        dimensions: { length_cm: 18, width_cm: 12, height_cm: 22 },
        package_type: 'box',
        fragile: false,
        featured: true
      },
      {
        name: 'Lodge 10.25-inch Seasoned Cast Iron Skillet',
        sku: 'PRD-HOM-50E',
        category: catHome._id,
        description: 'Pre-seasoned with 100% natural vegetable oil, superior heat retention for searing, baking, broiling, and frying.',
        short_description: 'Lodge 10.25-inch Seasoned Cast Iron Skillet.',
        price_coins: 21000,
        images: ['https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=500'],
        stock: 65,
        weight_kg: 2.4,
        dimensions: { length_cm: 40, width_cm: 27, height_cm: 5 },
        package_type: 'box',
        fragile: false,
        featured: false
      },
      {
        name: 'Ninja Professional 1000W Countertop Blender (72 oz Pitcher)',
        sku: 'PRD-HOM-50F',
        category: catHome._id,
        description: 'Total Crushing technology pulverizes ice to snow in seconds for smoothies, frozen drinks, and sauces.',
        short_description: 'Ninja Professional 1000W Countertop Blender.',
        price_coins: 41250,
        images: ['https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=500'],
        stock: 50,
        weight_kg: 3.8,
        dimensions: { length_cm: 25, width_cm: 20, height_cm: 42 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'Keurig K-Elite Single Serve K-Cup Pod Coffee Maker',
        sku: 'PRD-HOM-50G',
        category: catHome._id,
        description: 'Strong brew setting, iced coffee feature, 75oz water reservoir, brews 4, 6, 8, 10, and 12 oz cup sizes.',
        short_description: 'Keurig K-Elite Single Serve Pod Coffee Maker.',
        price_coins: 58500,
        images: ['https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=500'],
        stock: 40,
        weight_kg: 3.6,
        dimensions: { length_cm: 33, width_cm: 25, height_cm: 33 },
        package_type: 'box',
        fragile: true,
        featured: true
      },
      {
        name: 'iRobot Roomba i3+ EVO Self-Emptying Robot Vacuum',
        sku: 'PRD-HOM-50H',
        category: catHome._id,
        description: 'Empties itself into Clean Base for up to 60 days, smart mapping, 10x power-lifting suction, ideal for pet hair.',
        short_description: 'iRobot Roomba i3+ EVO Self-Emptying Vacuum.',
        price_coins: 145000,
        images: ['https://images.unsplash.com/photo-1558317374-067fb5f30001?w=500'],
        stock: 25,
        weight_kg: 6.8,
        dimensions: { length_cm: 40, width_cm: 35, height_cm: 45 },
        package_type: 'box',
        fragile: true,
        featured: true
      },

      // Automotive (+4)
      {
        name: 'Chemical Guys HOL148 16-Piece Arsenal Builder Car Wash Kit',
        sku: 'PRD-US-AUT-57',
        category: catAuto._id,
        description: 'Includes Torq Foam Blaster gun, Citrus Wash & Gloss, Butter Wet Wax, Silk Shine Dressing, Wheel Gel, and towels.',
        short_description: 'Chemical Guys 16-Piece Car Wash Kit with Foam Gun.',
        price_coins: 28500,
        images: ['https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?w=500'],
        stock: 60,
        weight_kg: 4.8,
        dimensions: { length_cm: 35, width_cm: 30, height_cm: 30 },
        package_type: 'box',
        fragile: false,
        featured: true
      },
      {
        name: 'Suaoki 800A Peak Portable Lithium Car Jump Starter Pack',
        sku: 'PRD-US-AUT-58',
        category: catAuto._id,
        description: '20,000mAh battery pack jump starts up to 6.0L gas or 5.0L diesel engines, dual USB charging ports and LED flashlight.',
        short_description: 'Suaoki 800A Portable Car Jump Starter Pack.',
        price_coins: 48000,
        images: ['https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=500'],
        stock: 50,
        weight_kg: 1.1,
        dimensions: { length_cm: 20, width_cm: 12, height_cm: 6 },
        package_type: 'box',
        fragile: true,
        featured: false
      },
      {
        name: 'Bosch Icon 26A Premium All-Weather Beam Wiper Blade Pair',
        sku: 'PRD-US-AUT-59',
        category: catAuto._id,
        description: 'Exclusive FX dual rubber compound resists heat and ozone deterioration, 40% longer life than premium blades.',
        short_description: 'Bosch Icon 26A Premium Wiper Blade Pair.',
        price_coins: 52500,
        images: ['https://images.unsplash.com/photo-1563720223185-11003d516935?w=500'],
        stock: 65,
        weight_kg: 0.8,
        dimensions: { length_cm: 68, width_cm: 8, height_cm: 4 },
        package_type: 'box',
        fragile: false,
        featured: false
      },
      {
        name: 'ChargePoint Home Flex Level 2 NEMA 14-50 EV Charger (50A)',
        sku: 'PRD-US-AUT-60',
        category: catAuto._id,
        description: 'Fast 240V Level 2 EV charging station up to 50 Amps, 9x faster than standard wall outlet. 23ft charging cable.',
        short_description: 'ChargePoint Home Flex 50A Level 2 EV Charger.',
        price_coins: 210000,
        images: ['https://images.unsplash.com/photo-1647427060118-4911c9821b82?w=500'],
        stock: 25,
        weight_kg: 6.5,
        dimensions: { length_cm: 35, width_cm: 28, height_cm: 18 },
        package_type: 'box',
        fragile: true,
        featured: true
      }
`;

// Insert the new 48 products right before DeliveryPricingRule creation in seed.js
seedContent = seedContent.replace('    // 5. Create Delivery Pricing Rules', `${new48ProductsCode}\n    ]);\n\n    // 5. Create Delivery Pricing Rules`);
// Remove duplicate array closing brackets if any
seedContent = seedContent.replace('    ]);\n\n    ]);', '    ]);');

fs.writeFileSync(seedPath, seedContent, 'utf8');
console.log('Appended 48 new products into seed.js successfully!');
